import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// Maybe use local fonts?

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head />
      <body>
        <nav className='bg-blue-500 text-white p-4'>
          <h1>Art Explorer</h1>
        </nav>
        {children}
      </body>
    </html>
  );
}
